language: python
os: linux
dist: trusty
# Required to get Trusty.
#sudo: true
python:
    - "3.7"
install:
    - "pip install -U pip virtualenv"
    - "pip install -r requirements.txt"
    # Ensure it's installable and usable in virtualenv
    - "virtualenv ~/venv"
    - "travis_wait 30 ~/venv/bin/pip -v install ."
    - "~/venv/bin/pip -v install nose"
# Can't be somewhere that has a 'bitshuffle' directory as nose will use that
# copy instead of installed package.
script:
  - "cd ~"
  - "nosetests -v bitshuffle"  # Test the system install
  - "venv/bin/nosetests -v bitshuffle"  # Test the virtualenv install
